[package]
name = "solang-parser"
version = "0.1.13"
authors = ["Sean Young <sean@mess.org>"]
homepage = "https://github.com/hyperledger-labs/solang"
documentation = "https://solang.readthedocs.io/"
license = "Apache-2.0"
build = "build.rs"
description = "Solang Solidity Parser"
keywords = [ "solidity", "parser" ]
edition = "2021"

[build-dependencies]
lalrpop = "0.19"

[dependencies]
lalrpop-util = "0.19"
phf = { version = "0.10", features = ["macros"] }
unicode-xid = "0.2.0"
itertools = "0.10"
