[package]
version = "0.1.0"
input_files = ["flipper.sol"]   # Files to be compiled. You can define multiple files as : input_files = ["file1", "file2", ..]
contracts = ["flipper"] # Contracts to include from the compiled files
import_path = []   
import_map = {}   # Maps to import. Define as  import_map = {map = "path/to/map1", map2 = "path/to/map2"}


[target]
name = "solana" # Valid targets are "solana" and "polkadot"

[debug-features]
prints = true   # Log debug prints to the environment.
log-runtime-errors = true   # Log runtime errors to the environment.
generate-debug-info = false  # Add debug info to the generated llvm IR.

[optimizations]
dead-storage = true
constant-folding = true
strength-reduce = true
vector-to-slice = true
common-subexpression-elimination = true
llvm-IR-optimization-level = "default"  # Set llvm optimizer level. Valid options are "none", "less", "default", "aggressive"

[compiler-output]
verbose = false    # show debug messages
#emit = "llvm-ir"   # Emit compiler state at early stage. Valid options are: "ast-dot", "cfg", "llvm-ir", "llvm-bc", "object", "asm".
#output_directory = "path/to/dir"   
#output_meta = "path/to/dir"  # output directory for metadata
std_json_output = false        # mimic solidity json output on stdout